version: '3.9'

services:
  web:
    build: .
    container_name: flask-app
    expose:
      - "5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis-server
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  redis-data:
